import type { Metadata } from 'next';
import { Geist, Geist_Mono, Poppins, Lato, Quicksand } from 'next/font/google';
import './globals.css';
import SideBard from '@/components/sideBar';
import ReduxProvider from '@/providers/ReduxProvider';
import AppWrapper from '@/components/appWrapper';
import Header from '@/components/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '700', '600', '500', '300', '200', '100', '800', '900'],
});

const lato = Lato({
  variable: '--font-lato',
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
});

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${lato.variable} ${quicksand.variable} antialiased flex flex-col`}
      >
        <ReduxProvider>
          <AppWrapper>
            <div className="flex max-w-[1440px] w-full self-center bg-background min-h-screen">
              <SideBard />
              <main className="flex flex-col flex-1 bg-[#FFFFFF]">
                <Header />
                {children}
              </main>
            </div>
          </AppWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
